Ride_SharingApp/Controllers/ApiControllers/DriversController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using Ride_SharingApp.Controllers;

namespace Ride_SharingApp.Controllers.ApiControllers
{
    public class DriversController : ApiController
    {
        private Ride_SharingDBEntities db = new Ride_SharingDBEntities();

        // GET: api/Drivers
        public IQueryable<Driver> GetDrivers()
        {
            return db.Drivers;
        }

        // GET: api/Drivers/5
        [ResponseType(typeof(Driver))]
        public IHttpActionResult GetDriver(int id)
        {
            Driver driver = db.Drivers.Find(id);
            if (driver == null)
            {
                return NotFound();
            }

            return Ok(driver);
        }

        // PUT: api/Drivers/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutDriver(int id, Driver driver)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != driver.DriverId)
            {
                return BadRequest();
            }

            db.Entry(driver).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DriverExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Drivers
        [ResponseType(typeof(Driver))]
        public IHttpActionResult PostDriver(Driver driver)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Drivers.Add(driver);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = driver.DriverId }, driver);
        }

        // DELETE: api/Drivers/5
        [ResponseType(typeof(Driver))]
        public IHttpActionResult DeleteDriver(int id)
        {
            Driver driver = db.Drivers.Find(id);
            if (driver == null)
            {
                return NotFound();
            }

            db.Drivers.Remove(driver);
            db.SaveChanges();

            return Ok(driver);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool DriverExists(int id)
        {
            return db.Drivers.Count(e => e.DriverId == id) > 0;
        }
    }
}

Ride_SharingApp/Controllers/DriversController.cs
using PagedList;
using Ride_SharingApp.Authentications;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace Ride_SharingApp.Controllers
{
   
    public class DriversController : Controller
    {
        private Ride_SharingDBEntities db = new Ride_SharingDBEntities();

        // GET: Drivers

        [Authorize(Roles = "AdminView")]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var Contacts = from s in db.Drivers
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                Contacts = Contacts.Where(s => s.DriverName.Contains(searchString));

            }
            switch (sortOrder)
            {
                case "name_desc":
                    Contacts = Contacts.OrderByDescending(s => s.DriverName);
                    break;
              
                default:  // Name ascending 
                    Contacts = Contacts.OrderBy(s => s.DriverName);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(Contacts.ToPagedList(pageNumber, pageSize));
        }






       [Authorize(Roles = "UserView")]
       public ActionResult ReadOnly(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var Contacts = from s in db.Drivers
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                Contacts = Contacts.Where(s => s.DriverName.Contains(searchString));

            }
            switch (sortOrder)
            {
                case "name_desc":
                    Contacts = Contacts.OrderByDescending(s => s.DriverName);
                    break;

                default:  // Name ascending 
                    Contacts = Contacts.OrderBy(s => s.DriverName);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(Contacts.ToPagedList(pageNumber, pageSize));
        }

        //// GET: Drivers/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Driver driver = db.Drivers.Find(id);
        //    if (driver == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(driver);
        //}

        // GET: Drivers/Create
        [Authorize(Roles = "AdminView")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Drivers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DriverId,DriverName,DriverCNIC,DriverEmail,DriverPhone,DriverAverageRating")] Driver driver)
        {
            if (ModelState.IsValid)
            {
                db.Drivers.Add(driver);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(driver);
        }

        // GET: Drivers/Edit/5
        [Authorize(Roles = "AdminView")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = db.Drivers.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // POST: Drivers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DriverId,DriverName,DriverCNIC,DriverEmail,DriverPhone,DriverAverageRating")] Driver driver)
        {
            if (ModelState.IsValid)
            {
                db.Entry(driver).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(driver);
        }

        // GET: Drivers/Delete/5
        [Authorize(Roles = "AdminView")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = db.Drivers.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // POST: Drivers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Driver driver = db.Drivers.Find(id);
            db.Drivers.Remove(driver);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ride_SharingApp/Views/Drivers/Create.cshtml
@model Ride_SharingApp.Controllers.Driver

@{
    ViewBag.Title = "Create";
}
@Html.Partial("AdminNav")

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Driver</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DriverName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DriverName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DriverName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DriverCNIC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DriverCNIC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DriverCNIC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DriverEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DriverEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DriverEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DriverPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DriverPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DriverPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DriverAverageRating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DriverAverageRating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DriverAverageRating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ride_SharingApp/Views/Drivers/Delete.cshtml
@model Ride_SharingApp.Controllers.Driver

@{
    ViewBag.Title = "Delete";
}
@Html.Partial("AdminNav")
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Driver</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DriverName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DriverName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DriverCNIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DriverCNIC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DriverEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DriverEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DriverPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DriverPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DriverAverageRating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DriverAverageRating)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Ride_SharingApp/Views/Drivers/Edit.cshtml
@model Ride_SharingApp.Controllers.Driver

@{
    ViewBag.Title = "Edit";
}
@Html.Partial("AdminNav")

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Driver</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DriverId)

        <div class="form-group">
            @Html.LabelFor(model => model.DriverName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DriverName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DriverName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DriverCNIC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DriverCNIC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DriverCNIC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DriverEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DriverEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DriverEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DriverPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DriverPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DriverPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DriverAverageRating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DriverAverageRating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DriverAverageRating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ride_SharingApp/Views/Drivers/Index.cshtml
@using PagedList;
@using PagedList.Mvc;  

@model PagedList.IPagedList<Ride_SharingApp.Controllers.Driver>

@{
    ViewBag.Title = "Drivers List";
}
@Html.Partial("AdminNav")

<h2>Drivers List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Drivers", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" class="btn btn-default"/>
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().DriverName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DriverCNIC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DriverEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DriverPhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DriverAverageRating)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DriverName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DriverCNIC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DriverEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DriverPhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DriverAverageRating)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DriverId }) |
           
            @Html.ActionLink("Delete", "Delete", new { id=item.DriverId })
        </td>
    </tr>
}
   
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Ride_SharingApp/Views/Drivers/ReadOnly.cshtml
@using PagedList;
@using PagedList.Mvc;

@model PagedList.IPagedList<Ride_SharingApp.Controllers.Driver>

@{
    ViewBag.Title = "Drivers List";
}
@Html.Partial("UserNav")
<h2>Drivers List</h2>

<p>

</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().DriverName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DriverCNIC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DriverEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DriverPhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DriverAverageRating)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DriverName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DriverCNIC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DriverEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DriverPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DriverAverageRating)
            </td>

        </tr>
    }

</table>

@using (Html.BeginForm("ReadOnly", "Drivers", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" class="btn btn-default" />
    </p>
}

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("ReadOnly",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))