Ride_SharingApp/Controllers/VehiclesController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Ride_SharingApp.Controllers
{
    public class VehiclesController : Controller
    {
        private Ride_SharingDBEntities db = new Ride_SharingDBEntities();

        // GET: Vehicles
        [Authorize(Roles = "AdminView")]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var Contacts = from s in db.Vehicles
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                Contacts = Contacts.Where(s => s.VehicleOwnerName.Contains(searchString));

            }
            switch (sortOrder)
            {
                case "name_desc":
                    Contacts = Contacts.OrderByDescending(s => s.VehicleOwnerName);
                    break;

                default:  // Name ascending 
                    Contacts = Contacts.OrderBy(s => s.VehicleOwnerName);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(Contacts.ToPagedList(pageNumber, pageSize));
        }


        // User 

       [Authorize(Roles = "UserView")]
       public ActionResult ReadOnly(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var Contacts = from s in db.Vehicles
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                Contacts = Contacts.Where(s => s.VehicleOwnerName.Contains(searchString));

            }
            switch (sortOrder)
            {
                case "name_desc":
                    Contacts = Contacts.OrderByDescending(s => s.VehicleOwnerName);
                    break;

                default:  // Name ascending 
                    Contacts = Contacts.OrderBy(s => s.VehicleOwnerName);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(Contacts.ToPagedList(pageNumber, pageSize));
        }


        // GET: Vehicles/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Vehicle vehicle = db.Vehicles.Find(id);
        //    if (vehicle == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(vehicle);
        //}

        // GET: Vehicles/Create
        [Authorize(Roles = "AdminView")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VehicleId,VehicleRegistrationNumber,VehicleOwnerName,VehicleModel")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                db.Vehicles.Add(vehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vehicle);
        }

        // GET: Vehicles/Edit/5
        [Authorize(Roles = "AdminView")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VehicleId,VehicleRegistrationNumber,VehicleOwnerName,VehicleModel")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        [Authorize(Roles = "AdminView")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehicle vehicle = db.Vehicles.Find(id);
            db.Vehicles.Remove(vehicle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ride_SharingApp/Views/Vehicles/Create.cshtml
@model Ride_SharingApp.Controllers.Vehicle

@{
    ViewBag.Title = "Create";
}
@Html.Partial("AdminNav")
<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehicle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VehicleRegistrationNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleRegistrationNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleRegistrationNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleOwnerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleOwnerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleOwnerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ride_SharingApp/Views/Vehicles/Delete.cshtml
@model Ride_SharingApp.Controllers.Vehicle

@{
    ViewBag.Title = "Delete";
}
@Html.Partial("AdminNav")
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VehicleRegistrationNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleRegistrationNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VehicleOwnerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleOwnerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VehicleModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleModel)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Ride_SharingApp/Views/Vehicles/Edit.cshtml
@model Ride_SharingApp.Controllers.Vehicle

@{
    ViewBag.Title = "Edit";
}
@Html.Partial("AdminNav")

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehicle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VehicleId)

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleRegistrationNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleRegistrationNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleRegistrationNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleOwnerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleOwnerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleOwnerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ride_SharingApp/Views/Vehicles/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model PagedList.IPagedList<Ride_SharingApp.Controllers.Vehicle>
@{
    ViewBag.Title = "Vehicle List";
}
@Html.Partial("AdminNav")
<h2>Vehicle List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Vehicles", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" class="btn btn-default" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().VehicleRegistrationNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().VehicleOwnerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().VehicleModel)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VehicleRegistrationNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VehicleOwnerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VehicleModel)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.VehicleId }) |
           
            @Html.ActionLink("Delete", "Delete", new { id=item.VehicleId })
        </td>
    </tr>
}

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Ride_SharingApp/Views/Vehicles/ReadOnly.cshtml
@using PagedList;
@using PagedList.Mvc;

@model PagedList.IPagedList<Ride_SharingApp.Controllers.Vehicle>

@{
    ViewBag.Title = "Vehicle List";
}
@Html.Partial("UserNav")
<h2>Vehicle List</h2>

<p>
   
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().VehicleRegistrationNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().VehicleOwnerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().VehicleModel)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleRegistrationNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleOwnerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleModel)
            </td>

        </tr>
    }


</table>

@using (Html.BeginForm("ReadOnly", "Vehicles", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" class="btn btn-default" />
    </p>
}

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("ReadOnly",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))